# -*- coding: utf-8 -*-
"""Lista 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFXo9GBeByaget1FM6rBf_qlLIR2uaxG

1) Leia uma matriz 4 x 4, conte e escreva quantos valores maiores que 10 ela possui.
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
ordem = int(input('Digite a ordem: '))
cont = 0
matriz = []
numero = []
for i in range(ordem):#linha
  matriz.append([0]*ordem)
for i in range(ordem):
  for j in range(ordem): #coluna
    print('M[',i+1,',',j+1,'] = ',sep='',end='') 
    matriz[i][j]= int(input(''))
for i in range(ordem):
  for j in range(ordem):
    if matriz[i][j] >10:
      cont+= 1
for i in range(ordem):
  for j in range(ordem):
    print(matriz[i][j],sep='',end=' ')
  print()
print('O total de números maior que 10:',cont)

"""4) Gerar e imprimir uma matriz de tamanho 10 x 10, onde seus elementos são da forma: 

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
nlinhas = 10
ncoluna = 10
matriz = []
for i in range(nlinhas):
  matriz.append([0]*ncoluna)
for i in range(nlinhas):
  for j in range(ncoluna):
    if i < j:
      matriz[i][j] =  2*i + 7*j- 2 
    elif i == j: 
      matriz[i][j] = 3**i - 1 
    else: 
      matriz[i][j] = 4*i*i*i - 5*j*j + 1
for i in range(nlinhas):
  for j in range(ncoluna):
    print(matriz[i][j],end=' ')
  print()

"""5) Leia uma matriz de ordem n, informada pelo usuário. Calcule a soma dos elementos que estão acima da diagonal principal. 

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
ordem = int (input('Digite o tamanho da matriz: '))
matriz = []
soma = 0
for i in range(ordem):
  matriz.append([0]*ordem)
for i in range(ordem):
  for j in range(ordem):
    print('M[',i+1,',',j+1,']')
    matriz[i][j] = int(input(''))
for i in range(ordem):
  for j in range(ordem):
    if j == i+1:
      soma+= matriz[i][j]



for i in range(ordem):
  for j in range(ordem):
    print('[',matriz[i][j],']',sep='',end=' ') 
  print()
print('A soma acima da diagonal principal foi de:',soma)

"""6) Leia uma matriz de ordem n, informada pelo usuário. Calcule a soma dos elementos que estão abaixo da diagonal principal.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
ordem = int (input('Digite a ordem:'))
matriz = []
soma = 0 
for i in range(ordem):
  matriz.append([0]*ordem)
for i in range(ordem):
  for j in range(ordem):
    print('[',i+1,',',j+1,']',sep='')
    matriz[i][j] = int(input(''))
for i in range(ordem):
  for j in range(ordem):
    if i == j+1:
      soma+= matriz[i][j]
for i in range(ordem):
  for j in range(ordem):
    print(matriz[i][j],sep='',end=' ')
  print()
print('A soma que está abaixo da diagonal principal foi:',soma)

"""7)Leia uma matriz de ordem n, informada pelo usuário.
Calcule a soma dos elementos que estão na diagonal
secundária.
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
ordem = int(input('Digite a ordem da matriz:'))
matriz = []
soma = 0
for i in range(ordem):
  matriz.append([0]*ordem)
for i in range(ordem):
  for j in range(ordem):
    print('M[',i+1,',',j+1,']',sep='',end=' ')
    matriz[i][j] = int(input(''))

for  i in range(ordem):
    for j in range(ordem):
      if i + j == ordem-1:
        soma += matriz[i][j]
  
for i in range(ordem):
  for j in range(ordem):
    print(matriz[i][j],sep='',end=' ')
  print()
print('A soma dos elementos na diagonal secundária foi: ',soma)