# -*- coding: utf-8 -*-
"""Projeto 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Zz4aG4ikB-U2e-VXVPQsilnWNRpu5j5
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
ordem = int(input('Digite o tamanho da matriz: '))
matriz = []
linha = []
coluna = []
for i in range(ordem): 
    matriz.append([0]*ordem)
for i in range(ordem):#linha
  for j in range(ordem): #coluna
    print('M[',i+1,',',j+1,']')   
    matriz[i][j] = int(input(''))#pega valores
    linha.append(matriz[i])
    coluna.append(matriz[j])
for i in range(ordem):#linha
  for j in range(ordem):#coluna
    print('[',matriz[i][j],']',end=' ',sep='')
  print()
diagonal = []
diagonal2 = []
#Percorrer e somar cada linha
  sl = []
for i in range(ordem):
      soma = 0
      for j in range(ordem):
          soma += mat[i][j]
      sl.append(soma)
  #Percorrer e somar cada coluna
  sc = []
  for j in range(ordem):
      soma = 0
      for i in range(ordem):
          soma += mat[i][j]
      sc.append(soma)
  #Soma da diagonal principal
  sd = 0
  soma = 0
  for i in range(ordem):
      soma += mat[i][i]
  sd = soma
  #Soma diagonal secundária 
  somadiagonal = []
  somadiagonal = []
for i in range(len(diagonal)):
  somadiagonal = diagonal[0]+diagonal[1]+diagonal[2]
  somadiagonal2 = diagonal2[0]+diagonal2[1]+diagonal2[2]
  if somadiagonal == somadiagonal2:

ordem = int(input('Digite o tamanho da matriz: '))
matriz = []
linha = []
coluna = []
def quadrado(martriz,ordem) 
  for i in range(ordem): 
      matriz.append([0]*ordem)
  for i in range(ordem):#linha
    for j in range(ordem): #coluna
      print('M[',i+1,',',j+1,']')   
      matriz[i][j] = int(input(''))#pega valores
      linha.append(matriz[i])
      coluna.append(matriz[j])
  for i in range(ordem):#linha
    for j in range(ordem):#coluna
      print('[',matriz[i][j],']',end=' ',sep='')
    print()
  diagonal = []
  diagonal2 = []
  if matriz[0][0]:#diagonal principal
    diagonal.append(matriz[0][0]) 
    if matriz[1][1]:
      diagonal.append(matriz[1][1])
      if matriz[2][2]:
        diagonal.append(matriz[2][2])
        if matriz[2][0]:#diagonal secundária
          diagonal2.append(matriz[2][0])
          if matriz[1][1]:
            diagonal2.append(matriz[1][1])
            if matriz[0][2]:
              diagonal2.append(matriz[0][2])
  somadiagonal = []
  somadiagonal = []
  for i in range(len(diagonal)):
    somadiagonal = diagonal[0]+diagonal[1]+diagonal[2]
    somadiagonal2 = diagonal2[0]+diagonal2[1]+diagonal2[2]
    if somadiagonal != somadiagonal2:
      return False

"""$$Leonardo$$

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 


'''
Um quadrado mágico é aquele dividido em linhas e colunas, com um número em cada posição e no qual a soma das linhas, colunas e diagonais é a mesma. Por exemplo, veja um quadrado mágico de lado 3, com números de 1 a 9:
8  3  4
1  5  9
6  7  2

Faça uma função que receba uma matriz e sua ordem. Essa função deve informar se a matriz forma um quadrado mágico. Em seguida, faça um programa que: 
1 - Solicita ao usuário a ordem da matriz;
2 - Faz a leitura da matriz;
3 - Imprime a matriz;
4 - Informa se a matriz digitada forma um quadrado mágico.
'''

#ij

#00 01 02 
#10 11 12
#20 21 22


def quadrado(matriz, ordem):
    somaprincipal = 0
    for  i in range(ordem):
        for j in range(ordem):
          if i + j == ordem -1:
            somaprincipal = somaprincipal + matriz[i][j]
    
    soma = 0
    for i in range(ordem):
      soma = soma + matriz[i][i]
    
    if soma != somaprincipal:
      return False


    for i in range(ordem):
      somalinhas = 0
      for j in range(ordem):
        somalinhas = somalinhas + matriz[i][j]
      if somalinhas != somaprincipal:
        return False
    
    for i in range(ordem):
      somacolunas = 0
      for j in range(ordem):
        somacolunas = somacolunas + matriz[j][i]
      if somacolunas != somaprincipal:
        return False
    return True

tam = int(input('Digite o tamanho da matriz:'))

matriz = [0] * tam
for i in range(tam):
  matriz[i] = [0] * tam

for i in range(tam):
  for j in range(tam):
    print('M [',i+1,',',j+1,']= ', sep ='', end= '')
    matriz[i][j] = int(input())

for i in range(tam):
  for j in range(tam):
    print(matriz[i][j],end=' ')
  print()
  
print()
if quadrado(matriz,tam):
  print('É um quadrado mágico!')
else:
  print('Não é um quadrado mágico')