# -*- coding: utf-8 -*-
"""Atividade 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-ixghSyztKFZIH6TKgHKQsqhCa4DT2b

Questão 1
"""

valor = 0
total = 0
maior = 0
idade = 0
while idade !=-1: 
  idade = int (input("Insira a idade: ")) 
  if idade !=-1: 
    sexo = (input("Insira o sexo: ")) 
    olhos = (input("Insira a cor dos olhos: ")) 
    cabelo = (input("Insira a cor do cabelo: ")) 
    if idade >= 18 and idade <=35: 
      if sexo == 'f' or 'feminino': 
        if olhos == 'v' or 'verdes': 
          if cabelo == 'l' or 'louros': 
            total += 1 
  if idade>maior: 
    maior = idade
print("A maior idade dos habitantes: ", maior)
print("Indivíduos do sexo feminino com olhos verdes, cabelos louros, e idade entre 18 e 35 anos:", total, end='')