# -*- coding: utf-8 -*-
"""Atividade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTUAZHTarqOX6F9j5nQrA0MFKbnN5w3S

**Atividade 1**
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
lados=int (input("Insira quantos lados tem polígono: "))
cm=float (input("Insira a medida dos lado em cm: "))
if lados==3:
  area=(cm**2*3**(1/2))/4
  print("TRIÂNGULO", area,"cm²")
elif lados<3:
    print("NÃO É UM POLÍGONO")
elif lados==4:
  area=(cm**2)
  print("QUADRADO", area, "cm²")
elif lados==5:
  print("PENTÁGONO")
else:
  print("POLÍGONO NÃO IDENTIFICADO")