# -*- coding: utf-8 -*-
"""Projeto I RASCUNHO_BETA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bafE7-STDrL7zfTG29k1Zj6HEgj9hifB

VERSÃO COM BUG 12.05.21
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
catalago = ['s','f','g','x']#lista provisória
catalago2 = ['s','f','g','x']#lista provisória
filmes = []#usuário 1
filmes2 = []#usuário 2
novalista1 = []#pegar valores diferentes caso tenha iguais 
novalista2 = []#pegar valores diferentes caso tenha iguais 
vezes = 2
usua1 = False
usua2 = False
print()
print('Catálago: ', catalago)
print()
print('Usuário 1')
for i in range(vezes):
    print('',catalago[i])
    usuario1 = input('Digite um filme: ')
    if usuario1 == catalago[i]:
      usua1 = True
      if usua1 == True:
        filmes.append(usuario1)
print()
print('Catálago: ', catalago)
print('Usuário 2')  
for i in range(vezes):
    print('',catalago[i])
    usuario2 = input('Digite um filme: ')
    if usuario2 == catalago2[i]:#falta resolver, posicao
      usua2 = True
      if usua2 == True:
        filmes2.append(usuario2)#resolvido
rec1 = []
posicao = 0
for i in range(vezes):
  if filmes[i] != filmes2[i]:#recomendação usuario 2 - bug
    rec1.append(filmes2[i])
rec2 = []
posicao = 0 
for i in range(vezes):
  if filmes2[i] != filmes[i]:#recomendação usuario 1
    rec2.append(filmes[i])
condicao = False #conclusão resolvido
print()
for i in range(len(rec1)):
  for j in range(len(rec2)):
    if rec1[i] != rec2[i]:
      condicao = True
if condicao == True:
  print('Recomendações de filme para o usuário 1: ',filmes2)
  print('Recomendações de filme para o usuário 2: ',filmes)

"""VERSÃO SEM BUG 13.05.21"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
catalago = ['Batman','Life','Minha mãe é uma peça','Meu malvado favorito','Dorry','Dois','Três','Quatro','cinco','seis']#lista provisória
filmes = []#usuário 1
filmes2 = []#usuário 2
vezes = 10
cont = 0
cont2 = 0
teste1 = True
teste2 = True
print()
print('Usuário 1')
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario1 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario1 == 'S':
      filmes.append(catalago[i])
    else: 
      filmes.append('')
      cont +=1
print()
print('Usuário 2')  
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario2 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario2 == 'S':
      filmes2.append(catalago[i])
    else:
      filmes2.append('')
      cont2 +=1 #contar as vezes que entrará no else
for i in range(vezes):
  if filmes[i] != filmes2[i]:
    teste1 = False
  if filmes2[i] != filmes[i]:
    teste2 = False


for i in range(cont):
  filmes.remove('')
for j in range(cont2):
  filmes2.remove('')

print()
print('Recomendações de filme para o usuário 1: ',filmes2)
print('Recomendações de filme para o usuário 2: ',filmes)

"""# **VERSÃO FINAL**"""

# Commented out IPython magic to ensure Python compatibility.

# %reset -f
catalago = ['Batman','Refém do Jogo','Minha mãe é uma peça','Meu malvado favorito','Jurassic Park','O poderoso chefão','À espera de um milagre','Toy Store','Procurando Nemo','Homens de Preto']#lista provisória
vezes = 10
rec1 = []#recomendação para usuário 1 
rec2 = []#recomendação para usuário 2
booleanos = [0]*vezes
booleanos2 = [0]*vezes
print()
print('Usuário 1')
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario1 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario1 == 'S':
      booleanos[i] = True
    else:  
      booleanos[i] = False
print()
print('Usuário 2')  
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario2 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario2 == 'S':
      booleanos2[i] = True
    else:  
      booleanos2[i] = False
for i in range(vezes):
  if (booleanos[i] == False) and (booleanos2[i] == True):
    rec1.append(catalago[i])
  elif (booleanos[i]== True) and (booleanos2[i] == False):
    rec2.append(catalago[i])
print()
print('Recomendações de filme para o usuário 1: ',rec1)
print('Recomendações de filme para o usuário 2: ',rec2)

