# -*- coding: utf-8 -*-
"""Projeto I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-bEEp-YJFI_Qqr-GYhAe2vJ6-adX_hW

Projeto I - Finalizado
"""

# Commented out IPython magic to ensure Python compatibility.

# %reset -f
catalago = ['Batman','Refém do Jogo','Minha mãe é uma peça','Meu malvado favorito','Jurassic Park','O poderoso chefão','À espera de um milagre','Toy Store','Procurando Nemo','Homens de Preto']#lista provisória
vezes = 10
rec1 = []#recomendação para usuário 1 
rec2 = []#recomendação para usuário 2
booleanos = [0]*vezes
booleanos2 = [0]*vezes
print()
print('Usuário 1')
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario1 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario1 == 'S':
      booleanos[i] = True
    else:  
      booleanos[i] = False
print()
print('Usuário 2')  
print()
print('Catálago: ', catalago)
for i in range(vezes):
    print([i+1],':',catalago[i])
    usuario2 = input('Digite "S" se já assistiu ou "N" para NÃO: ')
    if usuario2 == 'S':
      booleanos2[i] = True
    else:  
      booleanos2[i] = False
for i in range(vezes):
  if (booleanos[i] == False) and (booleanos2[i] == True):
    rec1.append(catalago[i])
  elif (booleanos[i]== True) and (booleanos2[i] == False):
    rec2.append(catalago[i])
print()
print('Recomendações de filme para o usuário 1: ',rec1)
print('Recomendações de filme para o usuário 2: ',rec2)