# -*- coding: utf-8 -*-
"""Atividade 1 Unidade II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ms87yxY5cv5atPmUghA0BcVRGqcx4rJS
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
def quadrado(matriz, ordem):
    somaprincipal = 0
    for  i in range(ordem):
        for j in range(ordem):
          if i + j == ordem -1:
            somaprincipal = somaprincipal + matriz[i][j]
    
    soma = 0
    for i in range(ordem):
      soma = soma + matriz[i][i]
    
    if soma != somaprincipal:
      return False


    for i in range(ordem):
      somalinhas = 0
      for j in range(ordem):
        somalinhas = somalinhas + matriz[i][j]
      if somalinhas != somaprincipal:
        return False
    
    for i in range(ordem):
      somacolunas = 0
      for j in range(ordem):
        somacolunas = somacolunas + matriz[j][i]
      if somacolunas != somaprincipal:
        return False
    return True

tam = int(input('Digite o tamanho da matriz:'))

matriz = [0] * tam
for i in range(tam):
  matriz[i] = [0] * tam

for i in range(tam):
  for j in range(tam):
    print('M [',i+1,',',j+1,']= ', sep ='', end= '')
    matriz[i][j] = int(input())

for i in range(tam):
  for j in range(tam):
    print(matriz[i][j],end=' ')
  print()
  
print()
if quadrado(matriz,tam):
  print('É um quadrado mágico!')
else:
  print('Não é um quadrado mágico')