# -*- coding: utf-8 -*-
"""lista 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13TjaCzTXqIlkLwLsv6vhx3-1NKF-vbIc

**Número 1**
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
letra=(input("Digite uma letra: "))
if letra==('a') or letra==('e') or letra==('i') or letra==('o') or letra==('u'):
  print("A letra é uma vogal")
else:
  print("A letra não é uma vogal")

"""**Número 2**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
nota1=float(input("Digite a sua nota 1: "))
nota2=float(input("Digite a sua nota 2: "))
resultado=(nota1+nota2)/2
if resultado>=7:
  print("Parabéns, você foi aprovado! A sua média foi:", resultado)
elif resultado>=5 and resultado<7:
  print("Prova final! A sua média: ", resultado)
elif resultado<5:
  print("Reprovado! A sua média foi: ", resultado)

"""**Número 3** 



"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
n1=int(input("Digite o primeiro número "))
n2=int(input("Digite o segundo número "))
n3=int(input("Digite o terceiro número "))
maior=n1
if (n2>=maior):
  maior=n2
if (n3>=maior):
  maior=n3
menor=n1
if (n2<=menor):
  menor=n2
  (n3<=menor)
  menor=n3
print("O número maior é:", maior)
print("O número menor é:", menor)

"""**Número 4**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
p1=float(input("Insira o valor do primeiro produto "))
p2=float(input("Insira o valor do segundo produto "))
p3=float(input("Insira o valor do terceiro produto "))
barato=p1
if (barato>p2):
  barato=p2
if (barato>p3):
  barato=p3
print("O produto mais barato é: ", barato)

"""**Número 5**

















"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
n1=int(input("Digite o primeiro número "))
n2=int(input("Digite o segundo número "))
n3=int(input("Digite o terceiro número "))
if n1>n2>n3:
  print("A ordem descrecente é: ", n1, n2, n3)
elif n1>n3>n2:
  print("A ordem descrecente é: ", n1, n3, n2)
elif n2>n3>n1:
  print("A ordem descrecente é: ", n2, n3, n1)
elif n2>n1>n3:
  print("A ordem descrecente é: ", n2, n1, n3)
elif n3>n2>n1:
  print("A ordem descrecente é: ", n3, n2, n1)
elif n3>n1>n2:
  print("A ordem descrecente é: ", n3, n1, n2)

"""**Número 6**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
turno=(input("Digite o turno que você estuda M/m, T/t, N/n "))
if turno=='M' or turno=='m':
  print("Você estuda no turno manhã")
elif turno=='T' or turno=='t':
  print("Você estuda pela tarde")
elif turno=='N' or turno=='n':
  print("Você estuda pela noite")
else: 
  print("Comando inválido!")

"""**Número 7**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
hora=int(input("Insira quantas horas você tralbalhou este mês: "))
valorhora=float(input("Insira o valor da hora: "))
bruto=float(hora*valorhora)
print("Salário bruto: R$:", bruto)
sindicato=(3*bruto)/100
fgts=(11*bruto)/100
ir1=bruto
ir2=(5*bruto)/100
ir3=(10*bruto)/100
ir4=(20*bruto)/100
if bruto<=900:
  descontosir=0
  print("(-)IR(0%):R$ 0,00")
elif bruto<=1500:
  bruto2=((bruto-ir2)-bruto)
  descontosir=bruto2
  print("(-)IR(5%):R$ ",ir2)
elif bruto<=2500:
  bruto3=((bruto-ir3)-bruto)
  descontosir=bruto3
  print("(-)IRS(10%):R$ ",ir3)
elif bruto>2500:
  bruto4=((bruto-ir4)-bruto)
  descontosir=bruto4
  print("(-)IRS(20%):R$ ",ir4)
print("Sindicato: R$ ",sindicato)
print("FGTS:R$ ", fgts)
descontos=((descontosir-sindicato)*-1)
print("Total de descontos:R$ ",descontos)
liquido=((descontos-bruto)*-1)
print("Salário liquido:R$ ",liquido)

"""**Número 8**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
dia=int(input("Digite um número de 1 a 7:   "))
if dia==(1):
  print("1-Domingo")
elif dia==(2):
  print("2-Segunda")
elif dia==(3):
  print("3-Terça")
elif dia==(4):
  print("4-Quarta")
elif dia==(5):
  print("5-Quinta")
elif dia==(6):
  print("6-Sexta")
elif dia==(7):
  print("7-Sábado")
else:
  print("Comando inválido!")

"""**Número 9**

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
a=float(input("Digite o valor de A: "))
b=float(input("Digite o valor de B: "))
c=float(input("Digite o valor de C: "))
delta=(b**2)-(4*a*c)
if a==0:
  print("A equação não é do segundo grau.")
elif delta<0:
  print("A equação não possui raízes, pois delta é negativo:", delta)
elif delta>0:
  x1=(-b)+(delta**(1/2))/(2*a)
  x2=(-b)-(delta**(1/2))/(2*a)
  print("A equação possui duas raízes:", x1, x2)

"""**Número 10**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
ano=int(input("Digite o ano "))
if ano % 4==0:
  print("O ano é bissexto")
else:
  print("O ano não é bissexto")

numero=int(input("Insira um número"))
numerod=numero
if numero>1000:
  print("valor inválido")
else:
  cen=numero//100
  numero=numero%100
  dez=numero//10
  numero=numero%10
  uni=numero
print(numerod,"=",cen,"centenas",dez,"dezenas","e",uni,"unidades")

"""**Número 12**"""

saque = int(input("Insira o valor do saque: "))
if saque<10 or saque>600:
  print("Valor inválido!")
else:
  notas100=saque//100
  saque= saque%100
  notas50=saque//50
  saque=saque%50
  notas10=saque//10
  notas10=saque%10
  notas5=saque//5
  saque=saque%5
  notas1=saque
  print("notas de 100", notas100)
  print("notas de 50", notas50)
  print("notas de 10", notas10)
  print("notas de 5:", notas5)
  print("notas de 1:", notas1)

"""**Número 13**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
print("Responda com 1 para SIM e 0 para NÃO")
telefone=int(input("Telefonou para a vítima? "))
local=int(input("Esteve no local do crime? "))
perto=int(input("Mora perto da vítima? "))
dever=int(input("Devia para a vítima? "))
trabalhou=int(input("Já trabalhou com a vítima? "))
tudo=(telefone+local+perto+trabalhou+dever)
if tudo==2:
  print("Você é suspeito")
elif tudo==3 or tudo==4:
  print("Você é cumplice ")
elif tudo==5:
  print("Você é assasino")
else:
  print("Você é inocente")

"""**Número 14**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
litros=float(input("Digite a quantidade de combustível: "))
tipo=(input("Digite 'G ou g' para Gasolina 'A ou a' para Álcool: "))
if tipo=='A' or tipo=='a':
  total=(litros*3.40)
  if litros<=20:
    desconto=(total*3)/100
    valor=(desconto-total)*-1 
  elif litros>20:
    desconto=(total*5)/100 
    valor=(desconto-total)*-1
elif tipo=='G' or tipo=='g':
  total=(litros*4.50)
  if litros<=20:
    desconto=(total*4)/100
    valor=(desconto-total)*-1
  elif litros>20:
    desconto=(total*6)/100
    valor=(desconto-total)*-1
print("O valor será de:R$", valor)

"""**Número 15**"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
morango=float(input("Digite em KG a quantidade de Morango: "))
maca=float(input("Digite em KG a quantidade de Maçã: "))
kg=(maca+morango)
if morango<=5:
  morango=(morango*2.50)
elif morango>5:
  morango=(morango*2.20)
if maca<=5:
  maca=(maca*1.80)
elif maca>5:
  maca=(maca*1.50)
bruto=(morango+maca)
if bruto>25 or kg>8:
  desconto=(bruto*10)/100
  descontotal=(bruto-desconto)
  print("O valor total é de:", descontotal)
else: 
  print("O valor total é de:", bruto)