# -*- coding: utf-8 -*-
"""lista 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11FEZo2K49JSXrfhg8tyzxredY27VxzDs

1) Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
valor=int(input("Digite um valor "))
while valor<0 or valor>10:
  valor=int(input("Digite um valor "))#irá repetir a mensagem de cima, pois o valor digitado não está entre 0 e 10
print("A nota digitada foi: ", valor)

"""2) Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
nome = str (input("Digite o seu nome: "))
senha = str (input("Digte a sua senha: "))
while nome==senha:
  print("A senha não pode ser igual ao nome, tente uma nova senha.")
  senha = str (input("Digte a sua senha: "))

"""3) Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento.
```
### Não consegui :(



"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
A = 80000
taxaA = 0.03
B = 200000
taxaB = 0.015
anos = 0

while A < B:
  A = A + taxaA * A 
  B = B + taxaB * B
  anos = anos + 1
print("São necessários: ", anos,"anos")

"""4) Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(1,21):
  print(i)
  
for i in range(1,21):
  print(i,end=" ")

"""5) Faça um programa que leia 10 números e informe o maior número."""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
maior = int (input("Insira um número: "))
for i in range(10):
  numero = int (input("Insira um número: "))
  if numero > maior:
    maior = numero
print('O maior valor digitado foi',maior)

"""6) Faça um programa que leia 10 números e informe a soma e a média dos números."""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
media = float
for i in range(10):
  num = int (input("Digite um número: "))
media=(num/10)
print("A média dos números digitados é de: ", media)

"""7) Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(1,51,2):
  print("Ímpar: ",i)

"""8) Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
n1 = int (input("Insira o primeiro número: "))
n2 = int (input("Insira o segundo número número: "))
n1=n1+1
for i in range(n1,n2):
  print(i, end=' ')

"""9) Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual número ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
valor = int (input("Digite um valor: "))
for i in range(1,11):
  resul=valor*i
  print(valor,"X",i,"=",resul)

"""10) Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
n1 = int (input("Insira a base: "))
n2 = int (input("Insira o expoente: "))
potencia=+1
for i in range(n2):
  potencia = potencia*n1
print(potencia)

"""11) Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números ímpares."""

contarpar = 0
contarimpar = 0
for i in range(10):
  numero = int (input("Digite um número:"))
  if numero % 2 == 0:
    contarpar = contarpar+1
  else:
    contarimpar = contarimpar+1
print("São pares:", contarpar, "São ímpares:", contarimpar)

"""12) A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
quantidade = int (input("Quantos valores? "))
penultimo = 1
ultimo = 1
print(penultimo,ultimo,end="")
for i in range(quantidade-2):
  proximo = ultimo+penultimo
  print(proximo,end=" ")
  penultimo = ultimo
  ultimo = proximo

"""13) Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
fatorial=1
valor = int (input("Digite um valor"))
for i in range(valor,0,-1):
  fatorial = fatorial*i
print("O vatorial de",valor,"é:",fatorial)

"""14) Faça um programa que, dado um conjunto de N números, determine o menor valor, o maior valor e a soma dos valores.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
quantidade = int (input("Quantos números você irá digitar: "))
maior = float (input("Digite um número: "))
soma = maior
for i in range(quantidade):
  numero = float (input("Digite um número: "))
  soma = numero
  if numero > maior:
    maior = numero
  elif numero < maior: 
    menor = numero
print("O maior: ",maior, "O menor: ",menor, "A soma: ",soma)

"""15) Faça um programa que peça um número inteiro e determine se ele é ou não um número primo. Um número primo é aquele que é divisível somente por ele mesmo e por 1.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
numero = int (input("Insira um número: "))
primo = True
for i in range(2,numero,1):
  if numero % i ==0:
    primo = False
if primo: 
  print("O numero é primo")
else: 
  print("O número não é primo")

"""16) Faça um programa que peça para n pessoas a sua idade, ao final o programa deverá verificar se a média de idade da turma varia entre 0 e 25,26 e 60 e maior que 60; e então, dizer se a turma é jovem, adulta ou idosa, conforme a média calculada.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f 
soma = 0
media = 0
idade = 0
total = idade
print("Digite '-1' a qualquer momento para encerrar o programa")
while idade != -1:
  idade = int (input("Digite a idade: "))
  total = total+idade
  soma = soma+1
  media = (total/soma)
if 0 <=media<=25:
    print("População jovem")
elif 26<=media<=60:
    print("População adulta")
elif media > 60:
    print("População idosa")

"""17) Faça um programa que calcule o número médio de alunos por turma. Para isto, peça a quantidade de turmas e a quantidade de alunos para cada turma. As turmas não podem ter mais de 40 alunos.

"""

alunos = int (input("Digite o número de alunos: "))
turmas = int (input("Digite o número de turmas: "))
media = alunos//turmas
while media>40:
  print("A média de alunos por turma foi de:",media,".", "Não é permitido mais de 40 alunos por turma, tente novamente.")
  alunos = int (input("Digite o número de alunos: "))
  turmas = int (input("Digite o número de turmas: "))
  media = alunos//turmas
print("A média de alunos por turma foi de: ",media)

"""18) Faça um programa que calcule o valor total investido por um colecionador em sua coleção de CDs e o valor médio gasto em cada um deles. O usuário deverá informar a quantidade de CDs e o valor pago em cada um."""

total = 0
cadacd=1
soma = 0
while cadacd !=0:
  cadacd = float (input("Digite o valor pago por cada CD: "))
  cadacacd = cadacd+divisao
  soma = soma+1
  total = total+cadacd 
  media = total/soma
print("Valor investido:R$",total)
print("O valor médio gasto:R$", media)

produto = int 
for i in range(produto, 51):

"""Questão 21"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
numero = int(input("Digite um número"))
for i in range (2,numero):
  if i % 2 == 1 and i != 2:
    print("",i)

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
numero = int (input("Insira um número: "))
primo = True
for i in range(2,numero,1):
  if numero % i ==0:
    primo = False
if primo: 
  print("O numero é primo")
else: 
  print("O número não é primo")

Questão 22

acid = 0
for i in range(5):
  cod = input("Digite o código da cidade: ")
  veic = input("Digite o número de veículos na cidade(Em 2019): ")
  acidente = input("Digite o número de acidentes de trânsito com vítimas(Em 2019): ")
  acid = acidente+1
  if acidente > acid:
    maior = acidente

"""Questão 24"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
soma = 0
resposta = 0
totalaluno = 1
maior = 0
menor = 0 
while soma !=1 or aluno !='N':#lembrar de mudar, ainda n terminei??
  entrada = input("Digite uma resposta(1 a 10): ")
  soma = soma+1
  if soma == 1:
    if entrada =='A':
      resposta = resposta+1
  elif soma == 2:
    if entrada =='B':
      resposta = resposta+1
  elif soma == 3:
    if entrada == 'C':
      resposta = resposta+1
  elif soma == 4:
    if entrada =='D':
      resposta = resposta+1
  elif soma == 5:
    if entrada =='E':
      resposta = resposta+1
  elif soma == 6:
    if entrada == 'E':
      resposta = resposta+1
  elif soma == 7:
     if entrada == 'D':
       resposta = resposta+1
  elif soma == 8:
     if entrada == 'C':
       resposta = resposta+1
  elif soma == 9:
    if entrada == 'B':
      resposta = resposta+1
  elif soma == 10:
    if entrada == 'A':
      resposta = resposta+1
  aluno = input("Outro aluno vai utilizar o sistema? Digte S para sim")
  if aluno =='S':
    totalaluno=totalaluno+1
    soma=0
    resposta = 0
    maior = 0
    menor = 0 
totalaluno = totalaluno+1
print("Total de alunos:", totalaluno)

turma1 = resposta/soma

print("A média de notas da turma foi : ", turma1 )

"""24 primeira versão 

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
soma = 0
soma2 = 0
resposta = 0
resposta2 = 0
totalaluno = 1
maior = 0
menor = 0 
while soma !=1:#lembrar de mudar, ainda n terminei??
  entrada = input("Digite uma resposta(1 a 10): ")
  soma = soma+1
  if soma == 1:
    if entrada =='A':
      resposta = resposta+1
  elif soma == 2:
    if entrada =='B':
      resposta = resposta+1
  elif soma == 3:
    if entrada == 'C':
      resposta = resposta+1
  elif soma == 4:
    if entrada =='D':
      resposta = resposta+1
  elif soma == 5:
    if entrada =='E':
      resposta = resposta+1
  elif soma == 6:
    if entrada == 'E':
      resposta = resposta+1
  elif soma == 7:
     if entrada == 'D':
       resposta = resposta+1
  elif soma == 8:
     if entrada == 'C':
       resposta = resposta+1
  elif soma == 9:
    if entrada == 'B':
      resposta = resposta+1
  elif soma == 10:
    if entrada == 'A':
      resposta = resposta+1
aluno = input("Outro aluno vai utilizar o sistema? ")
totalaluno = totalaluno+1
while soma2!=1 or aluno!='N':#LEMBRAR DE MUDAR PARA 10
  entrada = input("Digite uma resposta(1 a 10): ")
  soma2 = soma2+1
  if soma2 == 1:
    if entrada =='A':
      resposta2 = resposta2+1
  elif soma2 == 2:
    if entrada =='B':
      resposta2 = resposta2+1  
    elif soma2 == 3:
      if entrada == 'C':
        resposta2 = resposta2+1
  elif soma2 == 4:
    if entrada =='D':
      resposta2 = resposta2+1
  elif soma2 == 5:
    if entrada =='E':
      resposta2 = resposta2+1
  elif soma2 == 6:
    if entrada == 'E':
      resposta2 = resposta2+1
  elif soma2 == 7:
     if entrada == 'D':
       resposta2 = resposta2+1
  elif soma2 == 8:
     if entrada == 'C':
       resposta2 = resposta2+1
  elif soma2 == 9:
    if entrada == 'B':
      resposta2 = resposta2+1
  elif soma2 == 10:
    if entrada == 'A':
      resposta2 = resposta2+1
    soma2= 0
    aluno = input("Outro aluno vai utilizar o sistema? ")
print("Total de alunos:", totalaluno)
if maior<resposta:
  maior = resposta
elif maior<resposta2:
  maior = resposta
if maior>resposta:
  menor = resposta
elif menor>resposta2:
  menor = resposta
turma1 = resposta/soma
turma2 = resposta2/soma2
print("O maior total total de acertos: ", maior)
print("O menor número de acertos: ", menor)
print("A média de notas da turma foi : ", turma1 or turma2)