# -*- coding: utf-8 -*-
"""lista for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uiapEtOE4XeCkhwG5E572tqEvDMB2YyJ

1)Faça um programa que imprima na tela os valores entre 20 e 40.
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(20,41):
  print(i, end=" ")

"""2) Faça um programa que imprima na tela os valores pares entre 20 e 40.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(20,41,2):
  print(i, end=" ")

"""3 - Faça um programa que imprima os múltiplos de 5 entre 20 e 100.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(20,101,5):
  print(i, end=" ")

"""4 - Faça um programa que imprima os números de 40 a 20 em ordem decrescente.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(40,19,-1):
  print(i, end=" ")

"""Faça um programa que solicite ao usuário um valor entre 1 e 10. Imprima a tabuada desse número.

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
valor = int(input("Insira um valor:"))
for i in range(1,11):
  resultado=(valor*i)
  print(valor,"*",i,'=',resultado)

"""6 - Faça um programa que imprima os números de 1 a 100. Entretanto, os múltiplos de 4 devem ser substituídos pela palavra “PIM”. Saída esperada:
 1 2 3 PIM 5 6 7 PIM 9 10 11 PIM 13 14 …

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
for i in range(1,101):
  if i%4==0:
    print(end=" PIM ")
  else: 
    print(i,end=' ')

"""7 - Faça um programa que solicite ao usuário um valor entre 1 e 10. Imprima os números de 1 a 100, substituindo os múltiplos do valor fornecido pela palavra “PIM”.
Ex.: o usuário digita 7
1 2 3 4 5 6 PIM 8 9 10 11 12 13 PIM 15 16 17 18 19 20 PIM 22 …

"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
valor=int(input("Digite o valor: "))
for i in range(1,101):
  if i%valor==0:
    print(end=" PIM ")
  else:
    print(i,end=" ")

"""
8 - Faça um programa que imprima na tela os números entre dois valores fornecidos pelo usuário. Ex.: Usuário informa 7 e 15
7 8 9 10 11 12 13 14 15
"""

v1=int(input("Digite o primeiro valor: "))#v1== valor 1
v2=int(input("Digite o segundo valor: "))#v2== valor 2
v2=v2+1
for i in range(v1, v2):
  print(i, end=" ")

"""
9 - Faça um programa que leia 10 valores informados pelo usuário. Informe quantos valores foram pares e quantos valores foram ímpares.
"""

contarpar=0
contarimpar=0
for i in range(10):
  valor=int(input('Digite um valor: '))
  if valor%2==0:
    contarpar=contarpar+1
  else:
    contarimpar=contarimpar+1
print("Foram", contarpar,"pares", contarimpar,"ímpares")